"""clear

Revision ID: 071ed0f55a90
Revises: 
Create Date: 2023-07-02 16:14:05.505746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071ed0f55a90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_title', sa.String(), nullable=True),
    sa.Column('pnc', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=True),
    sa.Column('product_link', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('rrc', sa.Integer(), nullable=True),
    sa.Column('company_price', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('screen_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nm_id', sa.BIGINT(), nullable=True),
    sa.Column('vendor_code', sa.String(), nullable=True),
    sa.Column('salePriceU', sa.Integer(), nullable=True),
    sa.Column('priceU', sa.Integer(), nullable=True),
    sa.Column('clientSale', sa.Integer(), nullable=True),
    sa.Column('basicSale', sa.Integer(), nullable=True),
    sa.Column('rrc', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('suppliers')
    op.drop_table('reports')
    # ### end Alembic commands ###
